apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: all-in-one

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: n8n-ingress
        namespace: all-in-one
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
      spec:
        rules:
          - host: n8n.127.0.0.1.nip.io
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: n8n-master
                      port:
                        number: 5678
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: minio-ingress
        namespace: all-in-one
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
      spec:
        rules:
          - host: minio.127.0.0.1.nip.io
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: minio
                      port:
                        number: 9001
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: signoz-ingress
        namespace: all-in-one
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
      spec:
        rules:
          - host: signoz.127.0.0.1.nip.io
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: signoz-frontend
                      port:
                        number: 3301
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: rabbitmq-ingress
        namespace: all-in-one
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
      spec:
        rules:
          - host: rabbitmq.127.0.0.1.nip.io
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: rabbitmq
                      port:
                        number: 15672

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: n8n-master
        namespace: all-in-one
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: n8n-master
                resources:
                  requests:
                    cpu: 200m
                    memory: 512Mi
                  limits:
                    cpu: 1000m
                    memory: 1Gi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: n8n-worker
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: n8n-worker
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: n8n-runner
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: n8n-runner
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: postgres
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: postgres
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: minio
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: minio
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: signoz-clickhouse
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: clickhouse
                resources:
                  requests:
                    cpu: 250m
                    memory: 512Mi
                  limits:
                    cpu: 1000m
                    memory: 1Gi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: signoz-otel-collector
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: otel-collector
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: signoz-query-service
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: query-service
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: signoz-frontend
        namespace: all-in-one
      spec:
        template:
          spec:
            containers:
              - name: frontend
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    cpu: 250m
                    memory: 256Mi
