apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: all-in-one

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage/postgres.yaml
  - storage/redis.yaml
  - storage/minio.yaml
  - storage/rabbitmq.yaml
  - n8n/master.yaml
  - n8n/worker.yaml
  - n8n/runner.yaml
  - n8n/otel-config.yaml
  - signoz/signoz.yaml
