apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: all-in-one
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  N8N_DB_USER: "n8n_user"
  N8N_DB_PASSWORD: "${N8N_DB_PASSWORD}"
  SIGNOZ_DB_USER: "signoz_user"
  SIGNOZ_DB_PASSWORD: "${SIGNOZ_DB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: all-in-one
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: all-in-one
type: Opaque
stringData:
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: all-in-one
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
  PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: all-in-one
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
  N8N_RUNNERS_AUTH_TOKEN: "${N8N_RUNNERS_AUTH_TOKEN}"
  DB_POSTGRESDB_USER: "n8n_user"
  DB_POSTGRESDB_PASSWORD: "${N8N_DB_PASSWORD}"
