apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: all-in-one-tls
  namespace: all-in-one
spec:
  secretName: all-in-one-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - ${N8N_HOST}
    - minio.${DOMAIN}
    - signoz.${DOMAIN}
    - rabbitmq.${DOMAIN}
